import 'package:flutter/material.dart';

import 'app_colors.dart';

const appHeaderStyleLarge = TextStyle(fontSize: 28, fontWeight: FontWeight.w700, color: primaryColor);
const appHeaderStyle = TextStyle(fontSize: 24, fontWeight: FontWeight.w600, color: primaryColor);
const appHeaderStyleBlack = TextStyle(fontSize: 24, fontWeight: FontWeight.w600, color: textColorBlack);
const appSubHeaderStyle = TextStyle(fontSize: 18, fontWeight: FontWeight.w400, color: textColorGrey);
const textStyleBlackLarge = TextStyle(fontSize: 18, fontWeight: FontWeight.w500, color: textColorBlack);
const textStyleBlackSmall = TextStyle(fontSize: 14, fontWeight: FontWeight.w400, color: textColorBlack);
const textStyle = TextStyle(fontSize: 16, fontWeight: FontWeight.w400, color: textColorGrey);
const textStyleBold = TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: textColorGrey);
const textStyleLightGrey = TextStyle(fontSize: 16, fontWeight: FontWeight.w400, color: textColorLightGrey);
const textStyleSmallMedium = TextStyle(fontSize: 14, fontWeight: FontWeight.w400, color: textColorGrey);
const textStyleSmallBold = TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: textColorGrey);
const textStyleWhite = TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: Colors.white);
const textStyleWhiteLight = TextStyle(fontSize: 14, fontWeight: FontWeight.w400, color: Colors.white);
const textStyleWhiteSmall = TextStyle(fontSize: 12, fontWeight: FontWeight.w400, color: Colors.white);
const textStyleWhiteSmallMedium = TextStyle(fontSize: 14, fontWeight: FontWeight.w400, color: Colors.white);
const textStyleWhiteSmallBold = TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: Colors.white);
const textStylePrimary = TextStyle(fontSize: 16, fontWeight: FontWeight.w400, color: primaryColor);
const textStylePrimarySmall = TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: primaryColor);
const textStylePrimaryLarge = TextStyle(fontSize: 18.0, fontWeight: FontWeight.w700, color: primaryColor);
const textStyleSecondary = TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: secondaryColor);
const errorStyleRed = TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: textColorRed);
const successStyleGreen = TextStyle(fontSize: 16, fontWeight: FontWeight.w500, color: textColorGreen);
const titleStyle = TextStyle(fontSize: 16.0, fontWeight: FontWeight.w700, color: secondaryColor);
const titleStyleLarge = TextStyle(fontSize: 18.0, fontWeight: FontWeight.w700, color: secondaryColor);
const titleStyleLargeLight = TextStyle(fontSize: 18.0, fontWeight: FontWeight.w600, color: secondaryColor);
const headerStyle = TextStyle(fontSize: 35, fontWeight: FontWeight.w900);
const subHeaderStyle = TextStyle(fontSize: 16.0, fontWeight: FontWeight.w500);
const mainHeaderStyleBlack = TextStyle(fontSize: 35, fontWeight: FontWeight.w900, color: Colors.black);
const subHeaderStyleBlue = TextStyle(fontSize: 16.0, fontWeight: FontWeight.w900, color: Color(0xFF0099ff));
const titleStyleWhite = TextStyle(fontSize: 18.0, fontWeight: FontWeight.w700, color: Colors.white);
const titleStyleWhiteLight = TextStyle(fontSize: 18.0, fontWeight: FontWeight.w400, color: Colors.white);
const entryStyle = TextStyle(fontSize: 16.0, fontWeight: FontWeight.w400, color: Color(0xFF0099ff));
const subHeaderBlackLight = TextStyle(fontSize: 16.0, fontWeight: FontWeight.w200, color: Colors.black26);
const subHeaderGrey = TextStyle(fontSize: 14.0, fontWeight: FontWeight.w200, color: Colors.blueGrey);
const headerStyleBlack = TextStyle(fontSize: 16.0, fontWeight: FontWeight.w400, color:Colors.black);
const largeHeaderStyleBlack = TextStyle(fontSize: 24.0, fontWeight: FontWeight.w400, color:Colors.black);
const labelStyle = TextStyle(fontSize: 16.0, fontWeight: FontWeight.w400, color: textColorBlack);
const labelStyleBold = TextStyle(fontSize: 16.0, fontWeight: FontWeight.w700, color: textColorBlack);
const labelStyleBoldLight = TextStyle(fontSize: 16.0, fontWeight: FontWeight.w600, color: textColorBlack);
const normalText = TextStyle(fontSize: 22.0, color: Colors.black54);
const entryStyles = TextStyle(fontSize: 14.0, color:Color(0xFF1565C0));
const textStyles = TextStyle(fontSize: 18, fontWeight: FontWeight.w400, color: textColorGrey);
const greyText = TextStyle(fontSize: 16.0, color: Colors.black54);
const styleBlack = TextStyle(fontSize: 18.0, fontWeight: FontWeight.w400, color:Colors.black);